POST http://localhost:3001/addPlayer
Content-Type: application/json

{
    "infos": {
        "identifier": "fivem:867432",
        "creation": "25/05/2013",
        "firstname": "Onde",
        "lastname": "Folie"
    }
}