POST http://localhost:3001/addPlayer
Content-Type: application/json

{
    "infos": {
        "identifier": "fivem:6884688",
        "creation": "25/05/2023",
        "firstname": "Sun",
        "lastname": "Rong"
    }
}